### ISSUE TITLE
addon is not interacting with component

### ISSUE THREAD

**Issue by Santheepkumar** [bhishp/storybook-formik#6]
I am trying to create a story for simple form. i configured storybook and storybook-formik perfectly.. But still I cant interact with my component in storybook..

`import React from "react";
import { storiesOf } from "@storybook/react";
import { withFormik } from "storybook-formik";
import IncubateeForm from "../components/incubatee-form";

const variants = {
  Primary: "FormPrimary",
  Default: null,
};

// storiesOf("IncubateeForm", module).add("FormPrimary", () => <IncubateeForm />);

storiesOf("IncubateeForm", module)
  .addDecorator(withFormik)
  .add("FormPrimary", () => <IncubateeForm />, {
    formik: {
      initialValues: {
        businessModel: "blue",
        targetSector: "",
        incubateeStage: "Canada",
        incubatioSector: "Mexico",
      },
    },
  });
![Screenshot from 2020-07-14 15-00-49](https://user-images.githubusercontent.com/41126042/87409638-d8df1200-c5e2-11ea-8aec-4bb71e1b1fe6.png)
`

**Comment by bhishp** [comment]
It seems like your IncubateeForm is already wrapped in a `<Formik>` component. Unfortunately the decorator doesn't track the state in this case because it is unable to determine the internal state of the Formik component in `IncubateeForm`. Your code here is the equivalent of the entire Form example: https://github.com/bhishp/storybook-formik/blob/master/stories/example.stories.tsx#L102

It is hard to tell without seeing the source code of IncubateeForm but if you wanted to get your form working with this addon you could break-up your component and extract the Form body. Something like...

```js
// in incubatee-form.jsx

export const IncubateeFormBody = () => (
  <Form>
    <label>Business Model</label>
    <Field name="businessModel" />
     {/* ... all your other form fields and jsx here... */ }
  </Form>
)

export default IncubateeForm = () => (
  <Formik>
    <IncubateeFormBody />
  </Formik>
)

// in stories.jsx


import React from "react";
import { storiesOf } from "@storybook/react";
import { withFormik } from "storybook-formik";
import { IncubateeFormBody } from "../components/incubatee-form";

const variants = {
Primary: "FormPrimary",
Default: null,
};

storiesOf("IncubateeForm", module)
  .addDecorator(withFormik)
  .add("FormPrimary", () => <IncubateeFormBody /> , {
    formik: {
      initialValues: {
        businessModel: "blue",
        targetSector: "",
        incubateeStage: "Canada",
        incubatioSector: "Mexico",
      },
    },
  });
```


# Under-the-hood

The decorator works by wrapping formik Fields in a Formik component, then transmitting this state to the storybook Panel. It can be done because the the Formik state is all managed by the decorator code.

When I first wrote the decorator I tried to look at how I might be able to intercept the state of a Formik component internal to the application code but I couldn't work it out at the time but would be cool to hear any ideas on how to do it.
